steps:

  - label: Preview Test
    commands:
      - ./scripts/preview.sh test

  - label: Preview Prod
    commands:
      - ./scripts/preview.sh prod

  - wait

  - label: Up Test
    commands:
      - ./scripts/up.sh test

  - wait

  - label: Up Prod
    commands:
      - ./scripts/up.sh prod