steps:

  - label: Preview Test
    commands:
      - .\scripts\preview.cmd test

  - label: Preview Prod
    commands:
      - .\scripts\preview.cmd prod

  - wait

  - label: Up Test
    commands:
      - .\scripts\up.cmd test

  - wait

  - label: Up Prod
    commands:
      - .\scripts\up.cmd prod